### ISSUE TITLE
call ezdz() more than one

### ISSUE THREAD

**Issue by mada41** [jaysalvat/ezdz#9]
hi @jaysalvat ! great plugin.
Btw i have some question how if i call ezdz() more than one, the example when i build input file with javascript after page load. I have try but that will show "Error: Ezdz error - Method undefined does not exist.".

Maybe you have an idea? thanks

**Comment by holden** [comment]
We did something like:

    $('[type="file"]').ezdz
      text: '<i class="fa fa-picture-o"></i>'
    $('.image-uploader').each (index) ->
      uploaderName = $(this).find('input.attachment').attr("name")
      $('[type="file"][name="' + uploaderName + '"]').ezdz "preview", $(this).data('image-url')

Which seems to work, but has some small issues on some browsers.  Maybe someone else has a better work around?

**Comment by jaysalvat** [comment]
Hello,

I don't understand, EZDZ can be applied to several input fields. 

    $('input[type="file"]').ezdz();

What is the problem exactly? :)

**Comment by ZebThan** [comment]
The problem is not the multiple fields alone. The things are starting to be a bit tricky, when you want to have multiple fields AND preview pictures. If you do so, you will end up with same picture in both boxes. The code above solves this problem (by setting preview picture for every box separately).

There was also another problem. On some configurations, when there was no preview picture we've had a big black dot instead of text "drop an image" or whatever. It appears, that if you pass an empty attribute like that <div data-image-url> you are getting something weird on data('image -url"), and when you are put that output in the object.ezdz "preview", you are getting black dot in the box. It's weird, because it does not affect all users, only some of them. 

This code solves the problem described above, by not passing empty things to the preview:
```javascript
$('[type="file"]').ezdz
text: '<i class="fa fa-picture-o"></i>'
$('.image-uploader').each (index) ->    
  uploaderName = $(this).find('input.attachment').attr("name")
  imageUrl = $(this).data('image-url')
  if imageUrl.length
    $('[type="file"][name="' + uploaderName + '"]').ezdz "preview", imageUrl
```

I hope it will help someone. And by the way, thanks for the plugin, it works great.

**Comment by jaysalvat** [comment]
Are you using the last version?

**Comment by jaysalvat** [comment]
The code below works perfectly well to me.

    $('#file1, #file2').ezdz();
    $('#file1').ezdz('preview', '/img/preview1.jpg');
    $('#file2').ezdz('preview', '/img/preview2.jpg');

Am I missing something?

**Comment by ZebThan** [comment]
The fact, that you need to manually name the divs on the html side ^^
We have uploaders in a LOT of places (and I really mean it). Also, sometimes there is one uploader, sometimes there are two. The solution above will work for both cases. And if one day we will have 100 uploaders on one page it will still work (and there is no telling we won't need it). So yeah, with one page and one uploader it is ok. But EZDZ can automatically transform every uploader into drag and drop. Being forced to name every single input field on the site would be such a waste of this sexy feature :)
